### ISSUE TITLE
Get numeric value for decimal digits?

### ISSUE THREAD

**Issue by sbuberl** [JuliaLang/utf8proc#104]
Don't see any value for this in the property struct.   I was hoping to allow all decimal digits to build numbers in my program, but I need to know each value to generate the numbers.  Other libraries and languages can return this data.  I can stick with ASCII for now though.

Thanks.

**Comment by stevengj** [comment]
What I would recommend would be to NFKC-normalize your string first.    That will convert different codepoints for the Arabic/Western numerals like `"𝟜𝟖𝟩𝟼０"` to ASCII `"48760"`.

(If you want to handle non-Arabic decimal digits, like in Javanese or Khmer, then you have more problems than just converting the digits; e.g. some languages might write the digits in a different order.  And then there are other locale-dependent problems like different ways of writing a decimal point.)

**Comment by sbuberl** [comment]
I guess I was hoping digits in that category would be more or less the same behavior.  But if that's the not the case, I'll stick with ASCII and will be research the normalization later and decide if it I want to do it.

Thanks.

**Comment by stevengj** [comment]
(Normalization will not change non-Arabic numerals to Arabic, so you don't need to worry about non-Western scripts if you just NFKC-normalize and then look for ASCII.)
