### ISSUE TITLE
add custom JULIA normalization?

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/utf8proc#11]
For JuliaLang/julia#5903.   If utf8proc can have LUMP, then libmojibake can have JULIA.  Unless we want to keep this separate from libmojibake.

**Comment by jiahao** [comment]
A quick note that Unicode provides a [list of confusable characters](http://www.unicode.org/Public/security/8.0.0/confusables.txt) as part of [UAX 39](http://www.unicode.org/reports/tr39/#Confusable_Detection), which also provides a list of recommendations for [characters in identifier names](http://www.unicode.org/reports/tr39/#Identifier_Characters) given security concerns.

**Comment by stevengj** [comment]
@jiahao, I think we explicitly decided to reject these recommendations, along with NFKC normalization, in JuliaLang/julia#5434, in order to distinguish a wider array of mathematical symbols (e.g. `𝐇` vs. `H`).

**Comment by stevengj** [comment]
Upon reflection, I think the best thing would be to make this pluggable, by allowing the caller to supply a custom mapping function that is applied to the codepoints after normalization.

**Comment by StefanKarpinski** [comment]
Providing a "reasonable" set of confusable mathematical characters won't be too crazy though.

**Comment by stevengj** [comment]
Closed by #89.
