### ISSUE TITLE
Case conversion test fails on Alpine Linux

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/utf8proc#127]
Output from `make check`:
```
test/case
MISMATCH df != towupper(df) == 1e9e
line 0: utf8proc case conversion FAILED 1 tests.
make: *** [Makefile:148: check] Error 1
```
There are also an _extraordinary_ number of mismatches with the system `wcwidth`, though the width tests still pass.

**Comment by stevengj** [comment]
Is this our bug our a bug in Alpine Linux?

**Comment by ararslan** [comment]
Unclear and I'm not sure how to figure it out, so I figured I'd open an issue here to see if anyone had any ideas.

**Comment by stevengj** [comment]
I'm confused, it looks like the error message is saying that `utf8proc_toupper(0x00df)` is giving `0x00df`, which is not what utf8proc gives on my system (or yours, since Julia calls it).

**Comment by ararslan** [comment]
Sure enough:
```c
#include <stdio.h>
#include <inttypes.h>
#include <wctype.h>
#include "utf8proc.h"

int main(int argc, char** argv) {
    int32_t u = utf8proc_toupper(0x00df);
    int32_t w = towupper(0x00df);
    printf("utf8proc_toupper: %x\ntowupper: %x\n", u, w);
    return 0;
}
```
Output on Ubuntu:
```
utf8proc_toupper: df
towupper: df
```
Output on Alpine:
```
utf8proc_toupper: df
towupper: 1e9e
```
And yet,
```julia
julia> uppercase(Char(0xdf))
'ß': Unicode U+00df (category Ll: Letter, lowercase)
```
on both systems.

**Comment by ararslan** [comment]
So I guess it's Alpine's fault for returning a bogus value from `towupper`.

**Comment by ararslan** [comment]
cc @jirutka, maintainer of the utf8proc Alpine port, and @fabled, who maintains the musl-dev port (which contains, among other things, `wctype.h`).

**Comment by ararslan** [comment]
Since this isn't a utf8proc issue, I'll close this. Thanks for humoring me, Steven. :wink:

**Comment by stevengj** [comment]
Unless the uppercase mapping of 0x00df changed in Unicode 10 (since utf8proc currently uses the Unicode 9 tables)?

This [U+00df](https://www.fileformat.info/info/unicode/char/00df/index.htm) page says that U+1E9E is a "nonstandard uppercase," though.

**Comment by fabled** [comment]
cc @richfelker

**Comment by richfelker** [comment]
Regarding case mappings, this is intentional, not a bug:

https://git.musl-libc.org/cgit/musl/commit/src/ctype/towctrans.c?id=4674809bdf7a46041ac0152eea0a6363ceeca548

For wcwidth, I'd have to see what the mismatches are.

**Comment by stevengj** [comment]
I agree that there is an argument for supporting the nonstandard uppercase form here.

**Comment by richfelker** [comment]
Whether "ẞ" or "SS" is preferred is subject to cultural considerations, but the C locale system cannot represent the latter mapping. "ß" is obviously not a correct uppercase form for "ß".

It's been a while since I delved into the Unicode stability policy, but my understanding is that they *can't* (by their own policy) add new case mappings for characters that previously lacked them; even if that's wrong, they may want to avoid adding a nominal case mapping to a single character when the mapping to a sequence "SS" may be preferred in some cultures. I don't think these considerations detract from mapping to "ẞ" being the right thing to do in the limitations of the C locale framework.

**Comment by stevengj** [comment]
Regarding the width mismatches, I wonder if that is due to the treatment of east asian neutral?  See #83

**Comment by richfelker** [comment]
That thread (#83) is a mess. If there are people who want to solve the problem of whether certain scripts (or some characters from certain scripts) should be treated as wcwidth=2, there needs to be an organized effort, outside of a single software project like this, involving actual users/experts of the affected scripts, not pulling values out of some random font file (unifont), and there should be interest from key implementors in supporting the outcome before the process begins. Until then, musl (and afaik, also glibc) take a simple approach and assign width=1 to everything except to characters that were explicitly wide in legacy CJK charsets.

**Comment by stevengj** [comment]
You assign width=1 to combining characters?

**Comment by richfelker** [comment]
Sorry, I was not sufficiently precise. Of course nonspacing combining characters (Mn) and certain other nonspacing (most of Cf) characters are wcwidth=0, and control characters (nonprintable) are wcwidth=-1.

**Comment by stevengj** [comment]
> except to characters that were explicitly wide in legacy CJK charsets

I assume you mean "East Asian Wide" characters in UAX#11?  These aren't just legacy charsets — emoji were changed to wide in Unicode 9 IIRC.

**Comment by richfelker** [comment]
musl's definitions are derived programmatically from EastAsianWidth.txt from Unicode 10.0, and I don't see any emoji marked as wide in it. Aside from actual ideographic characters, the only characters I'm aware of which are marked full/wide are the ones present in legacy charsets.

**Comment by stevengj** [comment]
https://www.unicode.org/reports/tr11/tr11-31.html#ED4 says that characters with the property `Emoji_Presentation` should be treated as `East Asian Wide`

**Comment by richfelker** [comment]
Well it says they're classified as such, and in fact the ones with `Emoji_Presentation` are in `EastAsianWidth.txt` so they should already be marked wcwidth=2 in musl. I don't know why I didn't notice them before. I think that omits a lot of characters I thought of as "emoji" including classic dingbats etc.

**Comment by ararslan** [comment]
The full list of mismatches, all 340,000+ lines, is here: https://gist.github.com/ararslan/c7dfbfb0f9dff42940a394c79be0afe3

Taking the first few entries from there:
```
julia> Char(0xad)
'\uad': Unicode U+00ad (category Cf: Other, format)

julia> Char(0x378)
'\u378': Unicode U+0378 (category Cn: Other, not assigned)

julia> Char(0x379)
'\u379': Unicode U+0379 (category Cn: Other, not assigned)

julia> Char(0x380)
'\u380': Unicode U+0380 (category Cn: Other, not assigned)
```
It looks like musl assigns width 1 to unassigned code points.

**Comment by stevengj** [comment]
[U+00ad](http://www.fileformat.info/info/unicode/char/00AD/index.htm) is a soft hyphen, which is [an interesting case](http://jkorpela.fi/shy.html).  In some contexts it is used as a hyphenation hint and is not displayed, and in other cases it is displayed.  Many terminal environments do display it, but this is not required.

[U+0380](http://www.fileformat.info/info/unicode/char/0380/index.htm) and several of the other characters are unassigned code points.   It's not at all obvious what width we should use for these.   I suppose, from a probabilistic standpoint, an unassigned codepoint is probably more likely to be used for a width-1 character (e.g. a private encoding like Conscript) than a width-0 character.

[U+0601](https://www.fileformat.info/info/unicode/char/0601/index.htm) certainly doesn't look like zero width, and isn't rendered as zero width by any font that I have (e.g. a؁b).

**Comment by stevengj** [comment]
Note that there *already is* an "organized review effort, outside of any single software project", sponsored by the GNU project, by both language and typography experts, to identify standards-conformant terminal-compatible font metrics and glyphs for the *entirety of Unicode.*  The result is called GNU Unifont, and it is updated every time Unicode is updated.

The problem is not a lack of data or a lack of review, but rather it is the [xkcd standards problem](https://xkcd.com/927/) of getting everyone, up and down the stack, to agree on which data to use.

**Comment by richfelker** [comment]
I was not aware of any such aspect to the GNU Unifont project, and wasn't even aware that it's still maintained. If it's really trying to act as a standards process for character-cell metrics, that sounds great, but there seems to be a serious lack of publicity around it. I can't even find anything supporting that claim on their website. Last I looked at it, the glyphs for many scripts were not actually usable for writing using them, and many were double-width just because it turned out to be easier to draw something nice looking in 16x16 than 8x16 for certain characters.

**Comment by richfelker** [comment]
The above comment that started this:

https://github.com/JuliaLang/utf8proc/issues/127#issuecomment-385996652

was specifically about acting as a "standards process" with buy-in from implementors (wcwidth implementors being libc, also terminals, screen/tmux, etc.). I am not rejecting attempts to define a better wcwidth out-of-hand. I'm rejecting attempts to claim that unilateral decisions by a party with almost no stake and almost no input from users of the affected scripts should be a basis for our decisions.

**Comment by stevengj** [comment]
> a party with almost no stake and almost no input from users of the affected scripts

I'm not sure this is an accurate description of the Unifont developers.

**Comment by stevengj** [comment]
By the way, regarding emoji being width 2, the lack of recognition of this prior to Unicode 9 led to this amusing issue in Julia that directly led to our attempt to get better charwidth tables: JuliaLang/julia#3721
