### ISSUE TITLE
add charwidth property

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/utf8proc#2]
As discussed in JuliaLang/julia#6939, the `wcwidth` function is broken on many operating systems.   When we import the Unicode data, it would be good to add another field to our database in order to store the character width, so that we can provide an up-to-date character-width function.

**Comment by nalimilan** [comment]
Any news on the upstream inclusion of mojibake patches? I'd just like to make sure it will be ready when Julia 0.4 is released.

**Comment by stevengj** [comment]
I haven't heard back; just pinged them again.

**Comment by stevengj** [comment]
Now that we are the official utf8proc maintainers, I think we should go ahead and add a 2-bit `width` field to `utf8proc_property_t` and populate it via jiahao's algorithm.

**Comment by StefanKarpinski** [comment]
Yes!
