### ISSUE TITLE
rename to utf8proc

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/utf8proc#21]
The Public Software Group has asked us to officially take over maintenance of utf8proc, so we should rename this repo back to utf8proc in order to ease the transition for distros and other packagers/users of utf8proc.

@StefanKarpinski, can you do the honors?

**Comment by nalimilan** [comment]
This is really great news! So my comment at https://github.com/JuliaLang/libmojibake/issues/22 is out of place (one should never read messages in reverse order...).

**Comment by StefanKarpinski** [comment]
Done.

**Comment by stevengj** [comment]
Thanks @StefanKarpinski.   Do you also need to flip some switch to get Travis re-enabled?

**Comment by tkelman** [comment]
I think the summary "fork for continued development of utf8proc" is not so appropriate any more.

**Comment by stevengj** [comment]
Good point; @StefanKarpinski, can you change the summary?
