### ISSUE TITLE
cmake script

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/utf8proc#23]
It would be nice to include a `cmake` script (a `CMakeLists.txt` file) to make life easier for Windows users.   Since utf8proc is so simple, we can easily maintain both this and a `Makefile`.

**Comment by tkelman** [comment]
I'll do this. Should also turn on AppVeyor while we're at it. Are we targetting a 1.2.0 release some point soon, where we would want to get this in?

**Comment by stevengj** [comment]
I'd like to do a 1.2.0 release soon after #2 is resolved (since that will break ABI compatibility, though the API will still be backwards compatible).

**Comment by stevengj** [comment]
(PS. Don't bother trying to reproduce the data regeneration scripts in cmake.  Since we run those so rarely, it's reasonable to run them only on Unices.  Just make a minimal CMakeLists that builds libutf8proc from utf8proc.c)

**Comment by tkelman** [comment]
Yeah, I don't suspect it to be more than 20 lines, really.

We will want to disallow in-tree builds from cmake though, to avoid overwriting the existing makefiles.
