### ISSUE TITLE
web page

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/utf8proc#25]
It is probably a good idea to have a web page separate from the github README; at the very least we'll want to host a bunch of tarballs somewhere.  What is the best way to do this?  Put it on julialang somewhere?

Maybe we should have a `julialang.org/utf8proc` that redirects here for now, and will be updated later.  @StefanKarpinski or @jiahao, can you do this?  I want to have a quasi-permanent URL to give to the Public Software Group ASAP so that they can update their web links accordingly.

**Comment by tkelman** [comment]
@ViralBShah did one for openlibm recently, we could copy most of the same template

**Comment by nalimilan** [comment]
FWIW, tarballs can be attached to the release on the GitHub page.

**Comment by ViralBShah** [comment]
GitHub pages provides templates and also automatically includes tarballs etc.

See: http://openlibm.org/

**Comment by ViralBShah** [comment]
The easiest way to get started is to go to the settings for the project and setup Github pages with the Automatic Page generator.

**Comment by stevengj** [comment]
Sounds great, can @StefanKarpinski or someone with admin permission do this?

**Comment by ViralBShah** [comment]
I just created a utf8proc admin group with @stevengj and @jiahao. Can you see if you can do it now?

**Comment by stevengj** [comment]
Thanks, created at http://julialang.org/utf8proc

**Comment by nalimilan** [comment]
Cool, but I have the same remark as for openlibm: better provide links to release tarballs, instead of git master. Not sure how hard it is to adapt the GitHub template.

**Comment by stevengj** [comment]
Yes, tarballs for git master are not good.

**Comment by stevengj** [comment]
Ah, I figured it out: it is in the utf8proc repo, just do `git fetch; git checkout gh-pages` and then we can edit the HTML directly.

**Comment by stevengj** [comment]
Okay, I've linked the release tarballs.  Closing this issue as we now have a web page, although it could certainly be fleshed out a lot more.
