### ISSUE TITLE
utf8proc does not correctly handle the 66 Unicode "noncharacters"

### ISSUE THREAD

**Issue by ScottPJones** [JuliaLang/utf8proc#34]
`utf8proc` considers the 66 Unicode "noncharacters" to not be valid, however the Unicode standard specifically says that they are valid code points, and need to be handled correctly in conforming software.

**Comment by stevengj** [comment]
According to the Unicode FAQ they should still be category `Cn`, but we shouldn't return `UTF8PROC_ERROR_INVALIDUTF8` for these.

**Comment by ScottPJones** [comment]
Yes, precisely!

**Comment by stevengj** [comment]
Quickly looking through the code, it seems like the only place this comes up is in `utf8proc_iterate`, where it seems like `if (uc < 0 || ((uc & 0xFFFF) >= 0xFFFE))` should be replaced with `if (uc < 0)`.  Any others?

**Comment by ScottPJones** [comment]
I think that's all I'd seen also... will fix as soon as I find that bloody "round tuit"!

**Comment by pao** [comment]
Julia doesn't track master of external dependencies, like utf8proc, except when absolutely necessary. I think you can modify your local build to use master (you can probably figure it out from `deps/Makefile`) for testing purposes.

**Comment by stevengj** [comment]
I would clone utf8proc into a separate repository before making changes.  Editing git submodules is a recipe for trouble if you aren't a git guru.

**Comment by ScottPJones** [comment]
@stevengj Thanks, luckily, I'd already done that last night, after going crazy trying to figure out why deps/utf8proc didn't match my ScottPJones/utf8proc fork...
