### ISSUE TITLE
I've posted a pure Lua translation of this code

### ISSUE THREAD

**Issue by differentprogramming** [JuliaLang/utf8proc#44]
here: https://github.com/differentprogramming/lua-mojibake
(yes the original was still called mojibake when I got my copy).

It still needs a tiny amount of cleanup and some documentation, but it's been tested.
currently it works in luajit with 5.2 support on, and on lua 5.2
I'll do a little cleanup so that it works in lua 5.1 and 5.3 soon.

It has a few lua specific features, since lua doesn't have mutable strings it has the option of using other mutable formats for strings, such as arrays of codepoints, arrays of single characters, arrays of multibyte utf8 encoded characters and arrays of graphemes.

The bench test has been expanded a little bit.

It has a couple unused routines still too.

**Comment by tkelman** [comment]
Neat. Is there an action item here, or is this just a heads-up? I suppose we could put a link to "alternate implementation" or something in the readme maybe?
