### ISSUE TITLE
tag 1.3 release

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/utf8proc#50]
It seems like we should be ready for this.  To do:

- [x] merge #51 in some form
- [x] update NEWS and README files as needed
- [x] push "v1.3" tag
- [x] update the web site (`gh-pages` branch): version numbers, release notes (copied from NEWS), documentation (run `doxygen` to generate).

Is there anything else or should I go ahead and do this?

**Comment by tkelman** [comment]
Just to be on the safe side, could make sense to run some of Julia's tests locally against the master version of utf8proc?

**Comment by jiahao** [comment]
Dare we ask if this works on Windoze...?

**Comment by stevengj** [comment]
I will run Julia's tests (on MacOS).

**Comment by jiahao** [comment]
Passes on Julia.MIT.edu (Ubuntu 15.04 64bit)

**Comment by stevengj** [comment]
According to the [unifont maintainer](https://savannah.gnu.org/bugs/index.php?45395), they will release a new version with Unicode 8 support this Sunday, so I think we should hold off a couple of days so that we can update the charwidth tables.

**Comment by stevengj** [comment]
Julia passes on MacOS.

**Comment by tkelman** [comment]
win32 works fine too. win64 builds and is running tests now. I expect it should be okay, the changes since the previous dev version aren't that dramatic.

**Comment by stevengj** [comment]
Done.
