### ISSUE TITLE
 warning: comparison of integers of different signs

### ISSUE THREAD

**Issue by fgsch** [JuliaLang/utf8proc#60]
Adding -Wextra yields:

utf8proc.c:439:28: warning: comparison of integers of different signs: 'utf8proc_ssize_t' (aka 'long') and 'unsigned long' [-Wsign-compare]
      if (wpos < 0 || wpos > SSIZE_MAX/sizeof(utf8proc_int32_t)/2)
                      ~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This is an issue if a project embeds utf8proc and it's compiled with -Wextra -Werror.

**Comment by stevengj** [comment]
It wouldn't hurt to do `wpos > (utf8proc_ssize_t) (SSIZE_MAX/sizeof(utf8proc_int32_t)/2)`; could you submit a PR?

**Comment by fgsch** [comment]
Sure, I will do that.
