### ISSUE TITLE
syntax error: 'constant' compilation failure with MSVC 2015

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/utf8proc#63]
Leaving this as a to-do, mostly for myself. AppVeyor here looks like it's running the newest MSVC it can find, but I think this failure only happens when some other header gets included before `utf8proc.h`.
ref https://ci.appveyor.com/project/tkelman/julia/build/1.0.688

```
 /c/projects/julia/deps/srccache/libuv/compile cl -nologo -MD -Z7 -ftls-model=global-dynamic -D_WIN32_WINNT=0x0502 -I../support   -I/c/projects/julia/usr/include -I/c/projects/julia/usr/include  -DLIBRARY_EXPORTS -DUTF8PROC_EXPORTS  -c string.c -o /c/projects/julia/src/flisp/string.o
cl : Command line warning D9002 : ignoring unknown option '-ftls-model=global-dynamic' 
string.c
c:\projects\julia\usr\include\utf8proc.h(95): error C2059: syntax error: 'constant' 
make[2]: *** [/c/projects/julia/src/flisp/string.o] Error 2
```

This happens when I compile Julia as C, but not when I compile as C++. MSVC 2015 is the first version with enough C99 support to make this easily possible. Probably need to change some of the ifdefs to be version-specific to avoid a collision with C99 true/false.

**Comment by tkelman** [comment]
x-ref https://github.com/JuliaLang/utf8proc/pull/55/files#r70891071 which is preventing me from easily testing this in combination with julia at the moment

**Comment by tkelman** [comment]
There's a chance this may have gone away, but now I'm getting a whole bunch of
```
<repeating many times starting at line 6594>
c:\projects\julia\deps\build\utf8proc\utf8proc_data.c(13419): warning C4245: 'initializing': conversion from 'int' to 'utf8proc_uint16_t', signed/unsigned mismatch
c:\projects\julia\deps\build\utf8proc\utf8proc_data.c(13420): warning C4245: 'initializing': conversion from 'int' to 'utf8proc_uint16_t', signed/unsigned mismatch
utf8proc.c(169): warning C4242: '=': conversion from 'utf8proc_int32_t' to 'utf8proc_uint8_t', possible loss of data
utf8proc.c(172): warning C4244: '=': conversion from 'utf8proc_int32_t' to 'utf8proc_uint8_t', possible loss of data
utf8proc.c(178): warning C4244: '=': conversion from 'utf8proc_int32_t' to 'utf8proc_uint8_t', possible loss of data
utf8proc.c(183): warning C4244: '=': conversion from 'utf8proc_int32_t' to 'utf8proc_uint8_t', possible loss of data
utf8proc.c(196): warning C4242: '=': conversion from 'utf8proc_int32_t' to 'utf8proc_uint8_t', possible loss of data
utf8proc.c(199): warning C4244: '=': conversion from 'utf8proc_int32_t' to 'utf8proc_uint8_t', possible loss of data
utf8proc.c(209): warning C4244: '=': conversion from 'utf8proc_int32_t' to 'utf8proc_uint8_t', possible loss of data
utf8proc.c(214): warning C4244: '=': conversion from 'utf8proc_int32_t' to 'utf8proc_uint8_t', possible loss of data
```

**Comment by stevengj** [comment]
Looking at the corresponding source lines warnings look innocuous—the conversions from int32 to int8 are guarded by explicit checks on the value of the integer being converted, for example—though of course it would be good to get rid of them.

**Comment by stevengj** [comment]
Closing this as the original error seems to be gone.  The remaining warnings are #86.

**Comment by tkelman** [comment]
I think this was fixed by 59334e44999a527ee27f29e8dddd9daa1fda1980. If whatever Julia file had included stdbool.h before utf8proc.h, then it might have conflicts. If anyone ever tries to build Julia with MSVC pre-2013 they may have some issues, but LLVM's requirements would probably be a more serious blocker to that.

**Comment by stevengj** [comment]
utf8proc itself should be okay with MSVC pre-2013 now, I think; that's what the `_MSC_VER < 1800` is for.

**Comment by tkelman** [comment]
But possibly not if something else were to have defined true/false before including utf8proc.h, maybe? Not sure it's enough of a problem to worry about.

**Comment by stevengj** [comment]
I doubt it's something we should worry about; they can always define `__bool_true_false_are_defined` to follow the C99 spec.
