### ISSUE TITLE
Library version versus package release version...

### ISSUE THREAD

**Issue by ladar** [JuliaLang/utf8proc#64]
Having the utf8proc_version return the API/ABI version string is quite confusing. I like to call the version function during launch, and print the output to the console so I can easily confirm which version of a dependency my system is using. When the string that gets printed doesn't match up with the tarball I just installed it throws me off. I'm expecting something akin to what most autotools based Makefiles like call the PACKAGE_VERSION. Was the 1.3.0 string in the 1.3.1 tarball, and in the HEAD revision a mistake? If it was intentional, would you mind adding a utf8proc_release function? 

I'm attaching a possible patch that would use the Makefile MAJOR/MINOR/PATCH variables to construct the release version string. It is setup so you can easily add a "-pre" suffix to the release version string when the commit isn't a tagged tarball release.

[utf8proc.release.patch.txt](https://github.com/JuliaLang/utf8proc/files/73741/utf8proc.release.patch.txt)

**Comment by stevengj** [comment]
Failing to update the version number in the header file was a mistake, sorry.  A pull request would be welcome.

**Comment by ladar** [comment]
I wasn't sure. The comment in the header pointing at semver.org made me think the header file version was intentionally static to indicate API/ABI compatibility. And the Makefile version information, was based on the tag release string, and was meant to govern the name of the shared object file. By the way, the current head on github.com is showing 2.0.0 in the Makefile, and 1.3.0 in the header. I assume you don't need a pull request just to make those match? 

I can fork and create a pull which will update the version information provided by utf8proc_version() using defines during compile (like the patch above), and that would keep the dynamic version information correct. Automatically updating the utf8proc.h header based on the Makefile params will be a lot tougher. 

I could write a Makefile recipe which uses sed to parse and update the header easily enough, but that would be platform specific, and unless it was smart enough to only update when necessary, automatically touching the headers during each make process would deceive any dependencies (including those in external projects, like mine) into rebuilding, even though nothing as actually changed. 

The only thing I can think of is creating a utf8proc_version.h file, which wouldn't exist in the repo, and could be generated easily enough via Makefile, whenever it is missing. If the version.h file is also in the gitignore file, then someone building from a tarball would simply generate the correct strings automatically. Of course anyone updating their installation by pulling the latest from the repo would have the file leftover from a previous build, and Make wouldn't realize it needs updating. Again, this could be solved with slight of hand, but it gets tricky fast. 

I'm not saying we should add autotools, but I am open to suggestions? Personally, I'm not a fan having the same information in two places either, because I also forget to update both places. 

P.S. I'm also wondering if copies pulled from git should include a suffix like -pre, or -dev like the header comment suggests? Of course removing that when creating a tarball would be an extra step, easily forgotten, especially if you rely on creating a git tag to setup the tarball release, instead of assembling it manually (or via a Make recipe).

**Comment by ladar** [comment]
What about eliminating the version strings from the header file altogether? That would force the function call to get the information at runtime (instead of during compile time), but that is how my project handles this issue.

**Comment by stevengj** [comment]
It's true that we have two version numbers, one for API and one for ABI compatibility, and that in principle these can be different.   However, in a patch release (e.g. 1.3.0 to 1.3.1) we should always increment the patch number in both the API and the ABI version.

The preprocessor version numbers in the header file are useful if you want the same code to work with different utf8proc API versions.  Adapting to API changes cannot be done at runtime.

**Comment by stevengj** [comment]
Should be fixed now.

**Comment by ladar** [comment]
Confirmed. 

I updated my project, and everything looks good. Thank you.
