### ISSUE TITLE
Tag release with Unicode 9 support

### ISSUE THREAD

**Issue by petercolberg** [JuliaLang/utf8proc#72]
utf8proc fails to build on Debian due to not supporting the current Unicode data ([#829236](https://bugs.debian.org/829236)). As the bug is release critical, utf8proc and Julia are scheduled to be removed from Debian testing on 2016-08-14.

Could you tag a new release that includes support for Unicode 9 (#70)?

**Comment by stevengj** [comment]
Yes, we should definitely do this soon.  (We need to bump the GNU Unifont version used to compute font metrics first.)

In the future, it would be good to download test data only for the version of Unicode that we actually support, rather than the latest version.  Is there an archive URL for the test data from earlier Unicode versions?

**Comment by stevengj** [comment]
One concern is that older versions of Julia will not currently build with this version, due to changes in the `grapheme_break` API.

**Comment by stevengj** [comment]
Okay, I've updated the `NEWS`.   I noticed that we accidentally bumped the ABI version twice, once in #62 and once in #70, even though there was no intervening release, so I've changed the ABI version back to 2.0.0.

@Keno, anything else I'm forgetting before we can release?

**Comment by stevengj** [comment]
@tkelman, can you update the README with an AppVeyor status badge?     Since it seems to be [set up under your account](https://ci.appveyor.com/project/tkelman/utf8proc), I'm not sure how to get the status badge URL.

**Comment by Keno** [comment]
Can't think of anything you haven't covered :shipit:.

**Comment by stevengj** [comment]
Okay, v2.0 is tagged and released.

**Comment by petercolberg** [comment]
@stevengj I still get this warning:
```
 cc -O2 -fPIC -std=c99 -Wall -Wmissing-prototypes -pedantic -DUTF8PROC_EXPORTS -c -o utf8proc.o utf8proc.c
utf8proc.c: In function ‘grapheme_break_extended’:
utf8proc.c:287:7: warning: variable ‘lbc_override’ set but not used [-Wunused-but-set-variable]
   int lbc_override = lbc;
       ^
```

**Comment by stevengj** [comment]
@Keno, what's up with that warning?  Looks like some dead code?

**Comment by Keno** [comment]
Damn, yes we forgot to fix that.

**Comment by stevengj** [comment]
If it is just a harmless warning, I don't think it requires a new release, but please patch it.

**Comment by Keno** [comment]
Unfortunately it's not harmless for people who use the stateful api directly, but it does happen work for the internal code because `lbc == *state`.

**Comment by tkelman** [comment]
We can just say 2.0 (which should have used semver and been 2.0.0) has a critical broken bug and should not be used, if we release 2.0.1 immediately after.

**Comment by petercolberg** [comment]
Could you tag #73 and #78 for inclusion into a 2.0.1 release?

**Comment by stevengj** [comment]
Okay, I'll wait until those are merged, as soon as their tests are green.

**Comment by stevengj** [comment]
Okay, 2.0.1 is now tagged.

**Comment by petercolberg** [comment]
Thanks everyone!

**Comment by stevengj** [comment]
I'll submit a PR to julia shortly so that we can support Unicode 9 in Julia 0.5.

**Comment by tkelman** [comment]
Does Julia 0.4 build against utf8proc 2 without problems? I personally don't think debian should be doing that if we don't have things that way on our release-0.4 branch, but just curious.

**Comment by Keno** [comment]
> Does Julia 0.4 build against utf8proc 2 without problems? I personally don't think debian should be doing that if we don't have things that way on our release-0.4 branch, but just curious.

It should, yes.
