### ISSUE TITLE
C99 compatibility of bool declaration

### ISSUE THREAD

**Issue by ennorehling** [JuliaLang/utf8proc#90]
In utf8proc.h, true, false and bool are defined. They are reserved keywords in modern C (not just C++), and clash with those definitions.

    #  ifndef __cplusplus
    typedef unsigned char utf8proc_bool;
    enum {false, true};
    #  else
    typedef bool utf8proc_bool;
    #  endif

This breaks compilation on MSVC, and there is no preprocessor macro I can define to let utf8proc.h know that bool is already defined elsewhere. Aside from the C99 standard, it also breaks if the utf8proc.h header is included after one that also defines false and true (like stdbool.h, which can be tested for with the __bool_true_false_are_defined feature macro).

**Comment by stevengj** [comment]
It doesn't define `bool`, but it does define `false` and `true`, and you're right that these conflict with `stdbool.h` in C99.

**Comment by stevengj** [comment]
We shouldn't define `false` and `true` at all in the public header file, since we only use these internally.

**Comment by stevengj** [comment]
(They are not technically reserved words in C; it should be safe to define them in `utf8proc.c`, where we don't include `stdbool.h`.)

**Comment by stevengj** [comment]
On non-MS compilers, we include `stdbool.h`in C.  We didn't do so on MSVC because MS didn't provide that header...has that been fixed?

**Comment by stevengj** [comment]
Ah, I see that they finally fixed this in 2013.

**Comment by stevengj** [comment]
Should be fixed in master.
