### ISSUE TITLE
Unnecessary inclusion of system-dependent header file

### ISSUE THREAD

**Issue by H2CO3** [JuliaLang/utf8proc#93]
In [utf8proc.h, @ line 80](https://github.com/JuliaLang/utf8proc/blob/master/utf8proc.h#L80), `<sys/types.h>` is included. This header is not part of the C standard; it's POSIX-specific. It would be favorable to remove this include since it does not seem crucial — if the library uses types from this header at all, those types could be replaced by something more portable.

**Comment by nalimilan** [comment]
Would you make a pull request to remove it? If it passes the test, I guess that will confirm that the inclusion isn't needed.

**Comment by H2CO3** [comment]
Sure, here it is: https://github.com/JuliaLang/utf8proc/pull/94

**Comment by H2CO3** [comment]
@stevengj Thanks!
