### ISSUE TITLE
Makefile should not set MAKE

### ISSUE THREAD

**Issue by madscientist** [JuliaLang/utf8proc#95]
It's not really kosher for makefiles to set the `MAKE` variable themselves.  That variable is owned by the make program and it will set that variable itself to the appropriate value; by forcibly setting it yourself you're breaking any environment where the make program is named something different such as `gmake` or whatever.

**Comment by ararslan** [comment]
That seems to have been introduced in bc357b276f1fd7124bbb31a4e212a30e57520eee. cc @stevengj
